<?php
/**
 * @file		listuser.phtml
 *
 * @category   	Compassites
 * @package    	Compassites_View
 * @author     	Compassites Team
 * @copyright  	Copyright (c) 2011 Compassites (http://www.compassitesinc.com)
 *
 * @version		SVN: $Id: $
 */
$this->headLink()->appendStylesheet($this->baseUrl().'css/jquery.ui.css');
$this->headLink()->appendStylesheet($this->baseUrl().'css/lib/jquery.ui.jqgrid.css');

$this->headScript()->appendFile($this->baseUrl().'js/lib/jquery.jqgrid.js');
$this->headScript()->appendFile($this->baseUrl().'js/lib/jquery.jqgrid.locale.en.js');

$this->headScript()->appendFile($this->baseUrl().'/js/user.js');
?>

<div class="navlink">
	<a href="<?php echo $this->url(
									array(
										'module'=> 'admin',
										'controller'=> 'user',
										'action'=> 'registeruser',
									),
									'default',
									true);
			?>
	">
		Add User
	</a>
</div>

<?php
	if( !empty($this->message) )
	{
		echo '<div class="message warning">'. $this->message.'</div>' ;
	}
?>

<div class="clear"></div>
<table id="list" class="table_format"></table>
<div id="pager"></div>
