<?php
/**
 * @file		changepassword.phtml
 *
 * @category    Compassites
 * @package    	Compassites_View
 * @author     	Compassites Team
 * @copyright  	Copyright (c) 2011 Compassites (http://www.compassitesinc.com)
 *
 * @version		SVN: $Id: $
 */

	#CSS
	$this->headLink()->prependStylesheet($this->baseUrl().'/css/form.css');
?>

<div class="content_left">
	<h1>Change passowrd</h1>
	<?php
		if( !empty($this->message) )
		{
			echo '<div class="message warning">'. $this->message . '</div>';
		}
		echo $this->form;
	?>
</div>