<?php
/**
 * @file		forgotpassword.phtml
 *
 * @category    Compassites
 * @package    	Compassites_View
 * @author     	Compassites Team
 * @copyright  	Copyright (c) 2011 Compassites (http://www.compassitesinc.com)
 *
 * @version		SVN: $Id: $
 */

	#CSS
	$this->headLink()->prependStylesheet($this->baseUrl().'/css/form.css');


?>


<div id="forgotpassword" class="content_left">
	<h1>Forgot passowrd</h1>

	<?php
			if( !empty($this->message) )
			{
				echo '<div class="message warning">'. $this->message.'</div>';
			}
			echo $this->form;
	?>

</div>